-- ============================================================================
-- Define pallet items and their sprite / stage amounts here
-- ============================================================================
local keys = {
    h3_spriteKey = "h3_pallet",                  -- modded pallets all should have this in their spriteNames
    vEmptyPallet = "construction_01_5",          -- vanilla empty (brick) pallet with no option
    vBrickPallet = "construction_01_4",          -- vanilla brick pallet with the Take 20 bricks option
    vGoldPallet = "location_military_knox_01_1", -- vanilla gold pallet with Take 30 ingots option
}

local items = {
    {
        item = "Base.SteelIngot",
        icon = "Item_Ingot_Steel.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_01_0"},
            {amount = 10, resultSprite = "h3_pallet_01_1"},
            {amount = 15, resultSprite = "h3_pallet_01_2"},
            {amount = 20, resultSprite = "h3_pallet_01_3"},
            {amount = 25, resultSprite = "h3_pallet_01_4"},
            {amount = 30, resultSprite = "h3_pallet_01_5"},
            {amount = 35, resultSprite = "h3_pallet_01_6"},
            {amount = 40, resultSprite = "h3_pallet_01_7"},
            {amount = 45, resultSprite = "h3_pallet_01_8"},
            {amount = 50, resultSprite = "h3_pallet_01_9"},
            {amount = 55, resultSprite = "h3_pallet_01_10"},
            {amount = 60, resultSprite = "h3_pallet_01_11"},
            {amount = 65, resultSprite = "h3_pallet_01_12"},
            {amount = 70, resultSprite = "h3_pallet_01_13"},
            {amount = 75, resultSprite = "h3_pallet_01_14"},
            {amount = 80, resultSprite = "h3_pallet_01_15"},
            {amount = 85, resultSprite = "h3_pallet_01_16"},
            {amount = 90, resultSprite = "h3_pallet_01_17"},
        },
    },
    {
        item = "Base.GoldBar",
        icon = "Item_Ingot_Gold.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_02_0"},
            {amount = 10, resultSprite = "h3_pallet_02_1"},
            {amount = 15, resultSprite = "h3_pallet_02_2"},
            {amount = 20, resultSprite = "h3_pallet_02_3"},
            {amount = 25, resultSprite = "h3_pallet_02_4"},
            {amount = 30, resultSprite = "h3_pallet_02_5"},
            {amount = 35, resultSprite = "h3_pallet_02_6"},
            {amount = 40, resultSprite = "h3_pallet_02_7"},
            {amount = 45, resultSprite = "h3_pallet_02_8"},
            {amount = 50, resultSprite = "h3_pallet_02_9"},
            {amount = 55, resultSprite = "h3_pallet_02_10"},
            {amount = 60, resultSprite = "h3_pallet_02_11"},
            {amount = 65, resultSprite = "h3_pallet_02_12"},
            {amount = 70, resultSprite = "h3_pallet_02_13"},
            {amount = 75, resultSprite = "h3_pallet_02_14"},
            {amount = 80, resultSprite = "h3_pallet_02_15"},
            {amount = 85, resultSprite = "h3_pallet_02_16"},
            {amount = 90, resultSprite = "h3_pallet_02_17"},
        },
    },
    {
        item = "Base.IronIngot",
        icon = "Item_Ingot_Iron.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_03_0"},
            {amount = 10, resultSprite = "h3_pallet_03_1"},
            {amount = 15, resultSprite = "h3_pallet_03_2"},
            {amount = 20, resultSprite = "h3_pallet_03_3"},
            {amount = 25, resultSprite = "h3_pallet_03_4"},
            {amount = 30, resultSprite = "h3_pallet_03_5"},
            {amount = 35, resultSprite = "h3_pallet_03_6"},
            {amount = 40, resultSprite = "h3_pallet_03_7"},
            {amount = 45, resultSprite = "h3_pallet_03_8"},
            {amount = 50, resultSprite = "h3_pallet_03_9"},
            {amount = 55, resultSprite = "h3_pallet_03_10"},
            {amount = 60, resultSprite = "h3_pallet_03_11"},
            {amount = 65, resultSprite = "h3_pallet_03_12"},
            {amount = 70, resultSprite = "h3_pallet_03_13"},
            {amount = 75, resultSprite = "h3_pallet_03_14"},
            {amount = 80, resultSprite = "h3_pallet_03_15"},
            {amount = 85, resultSprite = "h3_pallet_03_16"},
            {amount = 90, resultSprite = "h3_pallet_03_17"},
        },
    },
    {
        item = "Base.CopperIngot",
        icon = "Item_Ingot_Copper.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_04_0"},
            {amount = 10, resultSprite = "h3_pallet_04_1"},
            {amount = 15, resultSprite = "h3_pallet_04_2"},
            {amount = 20, resultSprite = "h3_pallet_04_3"},
            {amount = 25, resultSprite = "h3_pallet_04_4"},
            {amount = 30, resultSprite = "h3_pallet_04_5"},
            {amount = 35, resultSprite = "h3_pallet_04_6"},
            {amount = 40, resultSprite = "h3_pallet_04_7"},
            {amount = 45, resultSprite = "h3_pallet_04_8"},
            {amount = 50, resultSprite = "h3_pallet_04_9"},
            {amount = 55, resultSprite = "h3_pallet_04_10"},
            {amount = 60, resultSprite = "h3_pallet_04_11"},
            {amount = 65, resultSprite = "h3_pallet_04_12"},
            {amount = 70, resultSprite = "h3_pallet_04_13"},
            {amount = 75, resultSprite = "h3_pallet_04_14"},
            {amount = 80, resultSprite = "h3_pallet_04_15"},
            {amount = 85, resultSprite = "h3_pallet_04_16"},
            {amount = 90, resultSprite = "h3_pallet_04_17"},
        },
    },
    {
        item = "Base.SilverBar",
        icon = "Item_Ingot_Silver.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_05_0"},
            {amount = 10, resultSprite = "h3_pallet_05_1"},
            {amount = 15, resultSprite = "h3_pallet_05_2"},
            {amount = 20, resultSprite = "h3_pallet_05_3"},
            {amount = 25, resultSprite = "h3_pallet_05_4"},
            {amount = 30, resultSprite = "h3_pallet_05_5"},
            {amount = 35, resultSprite = "h3_pallet_05_6"},
            {amount = 40, resultSprite = "h3_pallet_05_7"},
            {amount = 45, resultSprite = "h3_pallet_05_8"},
            {amount = 50, resultSprite = "h3_pallet_05_9"},
            {amount = 55, resultSprite = "h3_pallet_05_10"},
            {amount = 60, resultSprite = "h3_pallet_05_11"},
            {amount = 65, resultSprite = "h3_pallet_05_12"},
            {amount = 70, resultSprite = "h3_pallet_05_13"},
            {amount = 75, resultSprite = "h3_pallet_05_14"},
            {amount = 80, resultSprite = "h3_pallet_05_15"},
            {amount = 85, resultSprite = "h3_pallet_05_16"},
            {amount = 90, resultSprite = "h3_pallet_05_17"},
        },
    },
    {
        item = "Base.BrassIngot",
        icon = "Item_Ingot_Brass.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_06_0"},
            {amount = 10, resultSprite = "h3_pallet_06_1"},
            {amount = 15, resultSprite = "h3_pallet_06_2"},
            {amount = 20, resultSprite = "h3_pallet_06_3"},
            {amount = 25, resultSprite = "h3_pallet_06_4"},
            {amount = 30, resultSprite = "h3_pallet_06_5"},
            {amount = 35, resultSprite = "h3_pallet_06_6"},
            {amount = 40, resultSprite = "h3_pallet_06_7"},
            {amount = 45, resultSprite = "h3_pallet_06_8"},
            {amount = 50, resultSprite = "h3_pallet_06_9"},
            {amount = 55, resultSprite = "h3_pallet_06_10"},
            {amount = 60, resultSprite = "h3_pallet_06_11"},
            {amount = 65, resultSprite = "h3_pallet_06_12"},
            {amount = 70, resultSprite = "h3_pallet_06_13"},
            {amount = 75, resultSprite = "h3_pallet_06_14"},
            {amount = 80, resultSprite = "h3_pallet_06_15"},
            {amount = 85, resultSprite = "h3_pallet_06_16"},
            {amount = 90, resultSprite = "h3_pallet_06_17"},
        },
    },
    {
        item = "Base.AluminumIngot",
        icon = "media/textures/Item_Ingot_Aluminum.png",
        category = "Ingot",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  5, resultSprite = "h3_pallet_07_0"},
            {amount = 10, resultSprite = "h3_pallet_07_1"},
            {amount = 15, resultSprite = "h3_pallet_07_2"},
            {amount = 20, resultSprite = "h3_pallet_07_3"},
            {amount = 25, resultSprite = "h3_pallet_07_4"},
            {amount = 30, resultSprite = "h3_pallet_07_5"},
            {amount = 35, resultSprite = "h3_pallet_07_6"},
            {amount = 40, resultSprite = "h3_pallet_07_7"},
            {amount = 45, resultSprite = "h3_pallet_07_8"},
            {amount = 50, resultSprite = "h3_pallet_07_9"},
            {amount = 55, resultSprite = "h3_pallet_07_10"},
            {amount = 60, resultSprite = "h3_pallet_07_11"},
            {amount = 65, resultSprite = "h3_pallet_07_12"},
            {amount = 70, resultSprite = "h3_pallet_07_13"},
            {amount = 75, resultSprite = "h3_pallet_07_14"},
            {amount = 80, resultSprite = "h3_pallet_07_15"},
            {amount = 85, resultSprite = "h3_pallet_07_16"},
            {amount = 90, resultSprite = "h3_pallet_07_17"},
        },
    },
    {
        item = "Base.PropaneTank",
        icon = "Item_PropaneTank.png",
        category = "PropaneTank",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  1, resultSprite = "h3_pallet_08_0"},
            {amount =  2, resultSprite = "h3_pallet_08_1"},
            {amount =  3, resultSprite = "h3_pallet_08_2"},
            {amount =  4, resultSprite = "h3_pallet_08_3"},
            {amount =  5, resultSprite = "h3_pallet_08_4"},
            {amount =  6, resultSprite = "h3_pallet_08_5"},
            {amount =  7, resultSprite = "h3_pallet_08_6"},
            {amount =  8, resultSprite = "h3_pallet_08_7"},
            {amount =  9, resultSprite = "h3_pallet_08_8"},
            {amount = 10, resultSprite = "h3_pallet_08_9"},
            {amount = 11, resultSprite = "h3_pallet_08_10"},
            {amount = 12, resultSprite = "h3_pallet_08_11"},
            {amount = 13, resultSprite = "h3_pallet_08_12"},
            {amount = 14, resultSprite = "h3_pallet_08_13"},
            {amount = 15, resultSprite = "h3_pallet_08_14"},
            {amount = 16, resultSprite = "h3_pallet_08_15"},
        },
    },
    {
        item = "Base.ClayBrick",
        icon = "Item_ClayBrick_Fired.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount = 32, resultSprite = keys.vBrickPallet},
        },
    },
    {
        item = "Base.ConcretePowder",
        icon = "Item_Concrete_Powder.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  1, resultSprite = "h3_pallet_10_0"},
            {amount =  2, resultSprite = "h3_pallet_10_1"},
            {amount =  3, resultSprite = "h3_pallet_10_2"},
            {amount =  4, resultSprite = "h3_pallet_10_3"},
            {amount =  5, resultSprite = "h3_pallet_10_4"},
            {amount =  6, resultSprite = "h3_pallet_10_5"},
            {amount =  7, resultSprite = "h3_pallet_10_6"},
            {amount =  8, resultSprite = "h3_pallet_10_7"},
            {amount =  9, resultSprite = "h3_pallet_10_8"},
            {amount = 10, resultSprite = "h3_pallet_10_9"},
            {amount = 11, resultSprite = "h3_pallet_10_10"},
            {amount = 12, resultSprite = "h3_pallet_10_11"},
            {amount = 13, resultSprite = "h3_pallet_10_12"},
            {amount = 14, resultSprite = "h3_pallet_10_13"},
            {amount = 15, resultSprite = "h3_pallet_10_14"},
            {amount = 16, resultSprite = "h3_pallet_10_15"},
            {amount = 17, resultSprite = "h3_pallet_10_16"},
            {amount = 18, resultSprite = "h3_pallet_10_17"},
        },
    },
    {
        item = "Base.Dirtbag",
        icon = "Item_Sandbag.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  3, resultSprite = "h3_pallet_11_0"},
            {amount =  6, resultSprite = "h3_pallet_11_1"},
            {amount =  9, resultSprite = "h3_pallet_11_2"},
            {amount = 12, resultSprite = "h3_pallet_11_3"},
            {amount = 15, resultSprite = "h3_pallet_11_4"},
            {amount = 18, resultSprite = "h3_pallet_11_5"},
            {amount = 21, resultSprite = "h3_pallet_11_6"},
            {amount = 24, resultSprite = "h3_pallet_11_7"},
            {amount = 27, resultSprite = "h3_pallet_11_8"},
            {amount = 30, resultSprite = "h3_pallet_11_9"},
            {amount = 33, resultSprite = "h3_pallet_11_10"},
            {amount = 36, resultSprite = "h3_pallet_11_11"},
            {amount = 39, resultSprite = "h3_pallet_11_12"},
            {amount = 42, resultSprite = "h3_pallet_11_13"},
            {amount = 45, resultSprite = "h3_pallet_11_14"},
            {amount = 48, resultSprite = "h3_pallet_11_15"},
        },
    },
    {
        item = "Base.Sandbag",
        icon = "Item_Sandbag.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  3, resultSprite = "h3_pallet_12_0"},
            {amount =  6, resultSprite = "h3_pallet_12_1"},
            {amount =  9, resultSprite = "h3_pallet_12_2"},
            {amount = 12, resultSprite = "h3_pallet_12_3"},
            {amount = 15, resultSprite = "h3_pallet_12_4"},
            {amount = 18, resultSprite = "h3_pallet_12_5"},
            {amount = 21, resultSprite = "h3_pallet_12_6"},
            {amount = 24, resultSprite = "h3_pallet_12_7"},
            {amount = 27, resultSprite = "h3_pallet_12_8"},
            {amount = 30, resultSprite = "h3_pallet_12_9"},
            {amount = 33, resultSprite = "h3_pallet_12_10"},
            {amount = 36, resultSprite = "h3_pallet_12_11"},
            {amount = 39, resultSprite = "h3_pallet_12_12"},
            {amount = 42, resultSprite = "h3_pallet_12_13"},
            {amount = 45, resultSprite = "h3_pallet_12_14"},
            {amount = 48, resultSprite = "h3_pallet_12_15"},
        },
    },
    {
        item = "Base.Gravelbag",
        icon = "Item_Gravelbag.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  3, resultSprite = "h3_pallet_13_0"},
            {amount =  6, resultSprite = "h3_pallet_13_1"},
            {amount =  9, resultSprite = "h3_pallet_13_2"},
            {amount = 12, resultSprite = "h3_pallet_13_3"},
            {amount = 15, resultSprite = "h3_pallet_13_4"},
            {amount = 18, resultSprite = "h3_pallet_13_5"},
            {amount = 21, resultSprite = "h3_pallet_13_6"},
            {amount = 24, resultSprite = "h3_pallet_13_7"},
            {amount = 27, resultSprite = "h3_pallet_13_8"},
            {amount = 30, resultSprite = "h3_pallet_13_9"},
            {amount = 33, resultSprite = "h3_pallet_13_10"},
            {amount = 36, resultSprite = "h3_pallet_13_11"},
            {amount = 39, resultSprite = "h3_pallet_13_12"},
            {amount = 42, resultSprite = "h3_pallet_13_13"},
            {amount = 45, resultSprite = "h3_pallet_13_14"},
            {amount = 48, resultSprite = "h3_pallet_13_15"},
        },
    },
    {
        item = "Base.Claybag",
        icon = "Item_Sandbag.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  3, resultSprite = "h3_pallet_14_0"},
            {amount =  6, resultSprite = "h3_pallet_14_1"},
            {amount =  9, resultSprite = "h3_pallet_14_2"},
            {amount = 12, resultSprite = "h3_pallet_14_3"},
            {amount = 15, resultSprite = "h3_pallet_14_4"},
            {amount = 18, resultSprite = "h3_pallet_14_5"},
            {amount = 21, resultSprite = "h3_pallet_14_6"},
            {amount = 24, resultSprite = "h3_pallet_14_7"},
            {amount = 27, resultSprite = "h3_pallet_14_8"},
            {amount = 30, resultSprite = "h3_pallet_14_9"},
            {amount = 33, resultSprite = "h3_pallet_14_10"},
            {amount = 36, resultSprite = "h3_pallet_14_11"},
            {amount = 39, resultSprite = "h3_pallet_14_12"},
            {amount = 42, resultSprite = "h3_pallet_14_13"},
            {amount = 45, resultSprite = "h3_pallet_14_14"},
            {amount = 48, resultSprite = "h3_pallet_14_15"},
        },
    },
    {
        item = "Base.PlasterPowder",
        icon = "Item_Plaster_Powder.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  1, resultSprite = "h3_pallet_15_0"},
            {amount =  2, resultSprite = "h3_pallet_15_1"},
            {amount =  3, resultSprite = "h3_pallet_15_2"},
            {amount =  4, resultSprite = "h3_pallet_15_3"},
            {amount =  5, resultSprite = "h3_pallet_15_4"},
            {amount =  6, resultSprite = "h3_pallet_15_5"},
            {amount =  7, resultSprite = "h3_pallet_15_6"},
            {amount =  8, resultSprite = "h3_pallet_15_7"},
            {amount =  9, resultSprite = "h3_pallet_15_8"},
            {amount = 10, resultSprite = "h3_pallet_15_9"},
            {amount = 11, resultSprite = "h3_pallet_15_10"},
            {amount = 12, resultSprite = "h3_pallet_15_11"},
            {amount = 13, resultSprite = "h3_pallet_15_12"},
            {amount = 14, resultSprite = "h3_pallet_15_13"},
            {amount = 15, resultSprite = "h3_pallet_15_14"},
            {amount = 16, resultSprite = "h3_pallet_15_15"},
            {amount = 17, resultSprite = "h3_pallet_15_16"},
            {amount = 18, resultSprite = "h3_pallet_15_17"},
        },
    },
    {
        item = "Base.Log",
        icon = "Item_Logs.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  8, resultSprite = "h3_pallet_16_0"},
            {amount = 16, resultSprite = "h3_pallet_16_1"},
            {amount = 24, resultSprite = "h3_pallet_16_2"},
            {amount = 32, resultSprite = "h3_pallet_16_3"},
            {amount = 40, resultSprite = "h3_pallet_16_4"},
            {amount = 48, resultSprite = "h3_pallet_16_5"},
        },
    },
    {
        item = "Base.Plank",
        icon = "Item_Plank.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  4, resultSprite = "h3_pallet_17_0"},
            {amount =  8, resultSprite = "h3_pallet_17_1"},
            {amount = 12, resultSprite = "h3_pallet_17_2"},
            {amount = 16, resultSprite = "h3_pallet_17_3"},
            {amount = 20, resultSprite = "h3_pallet_17_4"},
            {amount = 24, resultSprite = "h3_pallet_17_5"},
            {amount = 28, resultSprite = "h3_pallet_17_6"},
            {amount = 32, resultSprite = "h3_pallet_17_7"},
            {amount = 36, resultSprite = "h3_pallet_17_8"},
            {amount = 40, resultSprite = "h3_pallet_17_9"},
            {amount = 44, resultSprite = "h3_pallet_17_10"},
            {amount = 48, resultSprite = "h3_pallet_17_11"},
        },
    },
    {
        item = "Base.SheetMetal",
        icon = "Item_SheetMetal.png",
        category = "Material",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount =  4, resultSprite = "h3_pallet_18_0"},
            {amount =  8, resultSprite = "h3_pallet_18_1"},
            {amount = 12, resultSprite = "h3_pallet_18_2"},
            {amount = 16, resultSprite = "h3_pallet_18_3"},
            {amount = 20, resultSprite = "h3_pallet_18_4"},
            {amount = 24, resultSprite = "h3_pallet_18_5"},
            {amount = 28, resultSprite = "h3_pallet_18_6"},
            {amount = 32, resultSprite = "h3_pallet_18_7"},
            {amount = 36, resultSprite = "h3_pallet_18_8"},
            {amount = 40, resultSprite = "h3_pallet_18_9"},
            {amount = 44, resultSprite = "h3_pallet_18_10"},
            {amount = 48, resultSprite = "h3_pallet_18_11"},
            {amount = 52, resultSprite = "h3_pallet_18_12"},
            {amount = 56, resultSprite = "h3_pallet_18_13"},
            {amount = 60, resultSprite = "h3_pallet_18_14"},
            {amount = 64, resultSprite = "h3_pallet_18_15"},
            {amount = 68, resultSprite = "h3_pallet_18_16"},
            {amount = 72, resultSprite = "h3_pallet_18_17"},
        },
    },
    {
        tag = "wholetire1",
        icon = "Item_CarTire.png",
        category = "Tire",
        stages = {
            {amount = 0, resultSprite = keys.vEmptyPallet},
            {amount = 1, resultSprite = "h3_pallet_19_0"},
            {amount = 2, resultSprite = "h3_pallet_19_1"},
            {amount = 3, resultSprite = "h3_pallet_19_2"},
            {amount = 4, resultSprite = "h3_pallet_19_3"},
            {amount = 5, resultSprite = "h3_pallet_19_4"},
        },
    },
    {
        tag = "wholetire2",
        icon = "Item_CarTire.png",
        category = "Tire",
        stages = {
            {amount = 0, resultSprite = keys.vEmptyPallet},
            {amount = 1, resultSprite = "h3_pallet_19_5"},
            {amount = 2, resultSprite = "h3_pallet_19_6"},
            {amount = 3, resultSprite = "h3_pallet_19_7"},
            {amount = 4, resultSprite = "h3_pallet_19_8"},
            {amount = 5, resultSprite = "h3_pallet_19_9"},
        },
    },
    {
        item = "wholetire3",
        icon = "Item_CarTire.png",
        category = "Tire",
        stages = {
            {amount = 0, resultSprite = keys.vEmptyPallet},
            {amount = 1, resultSprite = "h3_pallet_19_10"},
            {amount = 2, resultSprite = "h3_pallet_19_11"},
            {amount = 3, resultSprite = "h3_pallet_19_12"},
            {amount = 4, resultSprite = "h3_pallet_19_13"},
            {amount = 5, resultSprite = "h3_pallet_19_14"},
        },
    },
    {
        item = "Base.MoneyBundle",
        icon = "Item_Money_Stack.png",
        category = "Money",
        stages = {
            {amount =   0, resultSprite = keys.vEmptyPallet},
            {amount =   4, resultSprite = "h3_pallet_20_0"},
            {amount =   8, resultSprite = "h3_pallet_20_1"},
            {amount =  12, resultSprite = "h3_pallet_20_2"},
            {amount =  16, resultSprite = "h3_pallet_20_3"},
            {amount =  20, resultSprite = "h3_pallet_20_4"},
            {amount =  24, resultSprite = "h3_pallet_20_5"},
            {amount =  28, resultSprite = "h3_pallet_20_6"},
            {amount =  32, resultSprite = "h3_pallet_20_7"},
            {amount =  36, resultSprite = "h3_pallet_20_8"},
            {amount =  40, resultSprite = "h3_pallet_20_9"},
            {amount =  44, resultSprite = "h3_pallet_20_10"},
            {amount =  48, resultSprite = "h3_pallet_20_11"},
            {amount =  52, resultSprite = "h3_pallet_20_12"},
            {amount =  56, resultSprite = "h3_pallet_20_13"},
            {amount =  60, resultSprite = "h3_pallet_20_14"},
            {amount =  64, resultSprite = "h3_pallet_20_15"},
            {amount =  68, resultSprite = "h3_pallet_20_16"},
            {amount =  72, resultSprite = "h3_pallet_20_17"},
            {amount =  76, resultSprite = "h3_pallet_20_18"},
            {amount =  80, resultSprite = "h3_pallet_20_19"},
            {amount =  84, resultSprite = "h3_pallet_20_20"},
            {amount =  88, resultSprite = "h3_pallet_20_21"},
            {amount =  92, resultSprite = "h3_pallet_20_22"},
            {amount =  96, resultSprite = "h3_pallet_20_23"},
            {amount = 100, resultSprite = "h3_pallet_20_24"},
            {amount = 104, resultSprite = "h3_pallet_20_25"},
            {amount = 108, resultSprite = "h3_pallet_20_26"},
            {amount = 112, resultSprite = "h3_pallet_20_27"},
            {amount = 116, resultSprite = "h3_pallet_20_28"},
            {amount = 120, resultSprite = "h3_pallet_20_29"},
            {amount = 124, resultSprite = "h3_pallet_20_30"},
            {amount = 128, resultSprite = "h3_pallet_20_31"},
            {amount = 132, resultSprite = "h3_pallet_20_32"},
            {amount = 136, resultSprite = "h3_pallet_20_33"},
            {amount = 140, resultSprite = "h3_pallet_20_34"},
            {amount = 144, resultSprite = "h3_pallet_20_35"},
            {amount = 148, resultSprite = "h3_pallet_20_36"},
            {amount = 152, resultSprite = "h3_pallet_20_37"},
            {amount = 156, resultSprite = "h3_pallet_20_38"},
            {amount = 160, resultSprite = "h3_pallet_20_39"},
            {amount = 164, resultSprite = "h3_pallet_20_40"},
            {amount = 168, resultSprite = "h3_pallet_20_41"},
            {amount = 172, resultSprite = "h3_pallet_20_42"},
            {amount = 176, resultSprite = "h3_pallet_20_43"},
            {amount = 180, resultSprite = "h3_pallet_20_44"},
            {amount = 184, resultSprite = "h3_pallet_20_45"},
            {amount = 188, resultSprite = "h3_pallet_20_46"},
            {amount = 192, resultSprite = "h3_pallet_20_47"},
        },
    },
}

-- ============================================================================
-- Vanilla pallet resolver section
-- ============================================================================
-- this == brick def above but when I add custom textures I will need it anyway
local brickResolver = {
    {
        item = "Base.ClayBrick",
        icon = "Item_ClayBrick_Fired.png",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount = 32, resultSprite = keys.vBrickPallet},
        },
    },
}

-- only need 1 stage below vanilla sprite since options are Take or Take (All)
-- Add (All) option is variable based on inventory available though
local goldResolver = {
    {
        item = "Base.GoldBar",
        icon = "Item_Ingot_Gold.png",
        stages = {
            {amount =  0, resultSprite = keys.vEmptyPallet},
            {amount = 40, resultSprite = "h3_pallet_02_7"},
            {amount = 45, resultSprite = keys.vGoldPallet},
            {amount = 50, resultSprite = "h3_pallet_02_9"},
            {amount = 55, resultSprite = "h3_pallet_02_10"},
            {amount = 60, resultSprite = "h3_pallet_02_11"},
            {amount = 65, resultSprite = "h3_pallet_02_12"},
            {amount = 70, resultSprite = "h3_pallet_02_13"},
            {amount = 75, resultSprite = "h3_pallet_02_14"},
            {amount = 80, resultSprite = "h3_pallet_02_15"},
            {amount = 85, resultSprite = "h3_pallet_02_16"},
            {amount = 90, resultSprite = "h3_pallet_02_17"},
        },
    },
}

local vanillaPalletTable = {
    [keys.vEmptyPallet] = items,
    [keys.vBrickPallet] = brickResolver,
    [keys.vGoldPallet] = goldResolver,
}

return {
    items = items,
    keys = keys,
    vanillaPalletTable = vanillaPalletTable
}